### ISSUE TITLE
Question: Displaying embeded HTML in markdown

### ISSUE THREAD

**Issue by caraya** [Juicy/juicy-markdown#7]
I'm working on a project that pulls data from a third party API. The Markdow contains HTML content that is not rendered with juicy-markdown. For example:

To access the free version of this course, click the blue button that says &lt;em>Access Course Materials.&lt;/em> is rendered with HTML markup instead of rendering italics for em

&lt;a href="https://www.udacity.com/course/ud853" target="_blank">Developing Android Apps</a>. Following Android's &lt;a href="http://developer.android.com/distribute/essentials/quality/core.html" target="_blank">Core App Quality Guidelines</a>, we'll identify the production criteria that still needs to be implemented, then tackle each problem until Sunshine is ready to publish on the Google Play Store. In the process, we'll introduce you to a host of tools and concepts, including: material design approaches, image-handling, performance profiling, and more!

Is there a workaround for this?

**Comment by tomalec** [comment]
Sorry, but I didn't get how would you liek this to work. Could you provide jsbin/jsfiddle with sample code?

**Comment by caraya** [comment]
it should render the html. For example:

<a href="https://www.udacity.com/course/ud853" target="_blank">Developing Android Apps&lt;/a>. 

Should render as a hyperlink and not put the code in the markdown.  If I use marked-element component it renders the markup as a link.

**Comment by tomalec** [comment]
Sorry, maybe it's because it's quite late at my timezone, but I'm still not sure If I get your problem correctly.

AFAIK for `marked-element` you need to provide content inside `<script type="text/markdown">` and it will be parsed by marked. 

1. If you would like to be able, to put a child note that will be put before/after parsed stuff from  `value` or even content of `<script type="text/markdown">`.
 Like:
 ```html
<juicy-markdown value="## Content from attr">
    <a href="/smth">Inner HTML link</a>
</juicy-markdown>
```
 to be rendered as
 ```html
<h2>Content from attr</h2>
<a href="/smth">Inner HTML link</a>
```
  I think it's a idea worth trying, and should be doable after small change.

2. If you want to render
 ```md
## something in mardown syntax
That contains
<a href="https://www.udacity.com/course/ud853" target="_blank">Developing Android Apps</a>.
```
 as
 ```html
<h2>something in mardown syntax</h2>
That contains
&lt;a href="https://www.udacity.com/course/ud853" target="_blank"&gt;Developing Android Apps&lt;/a&gt;.
```
 using juicy-markdown, you should be able to do it right now, (examples are in index.html )

**Comment by caraya** [comment]
The issue is 2. I will retest the issue and post here if the issue persists
